# Add your Gemini API key here
# Get your API key from: https://makersuite.google.com/app/apikey

GEMINI_API_KEY = ""

# Replace "your-gemini-api-key-here" with your actual Gemini API key
# The key should look something like: abcdxyz...